/* eslint-disable no-unused-vars */

export enum Actions {
  CART_ADD_ITEM = 'CART_ADD_ITEM',
  CART_DELETE_ITEM = 'CART_DELETE_ITEM',
  CART_UPDATE_ITEM = 'CART_UPDATE_ITEM',
  CART_DELETE = 'CART_DELETE',
  SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS',
  SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD',
}
